### ISSUE TITLE
Add Cuda 9 Support

### ISSUE THREAD

**Issue by cjue** [fzi-forschungszentrum-informatik/gpu-voxels#63]
The changes to thrust and cub internals cause compilation errors like this one from issue #59 

```
[ 72%] Building NVCC (Device) object packages/gpu_voxels/src/gpu_voxels/octree/CMakeFiles/gpu_voxels_octree_CUDA_TARGET.dir/gpu_voxels_octree_CUDA_TARGET_generated_Octree.cu.o
In file included from /home/andreas/GPU-Voxels/gpu-voxels/packages/gpu_voxels/src/gpu_voxels/octree/Octree.cu:15:0:
/home/andreas/GPU-Voxels/gpu-voxels/packages/gpu_voxels/src/gpu_voxels/octree/NTree.hpp:56:43: fatal error: thrust/system/cuda/detail/cub.h: No such file or directory
compilation terminated.
```

**Comment by cjue** [comment]
The compilation errors are now fixed with release 1.1: https://github.com/fzi-forschungszentrum-informatik/gpu-voxels/commit/d9914ac10e82e50415af1cf7f175a406f99b4cd4

The voxelmap related unit tests now work with Cuda 9.1, but there are still run-time errors when using octrees or voxellists. We are investigating the causes of these issues.

**Comment by cjue** [comment]
Fixed with release 1.1.2
